config/routes.rb
Rails.application.routes.draw do

  root to: 'articles#index'
  
  get 'articles/new', to: 'articles#new', as: :new_articles
  get 'articles/:id', to: 'articles#show'
  get 'articles/:id/edit', to: 'articles#edit'

  patch 'articles/:id', to: 'articles#update', as: :article

  post 'articles', to: 'articles#create'

  delete 'articles/:id', to: 'articles#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_rich_text :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :find_article, only: [:show, :edit, :update, :destroy]

    def find_article
        @article = Article.find(params[:id])
    end

    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.create(article_params)
        
        redirect_to @article
    end

    def update
        @article.update(article_params)

        redirect_to @article
    end

    def destroy
        @article.destroy

        redirect_to root_path
    end

    def article_params
        params.require(:article).permit(:title, :content)
    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<div class="jumbotron">
    <h3 class="p-jumbotron">
        <%= article.title %>
    </h3>
    <h5 class="p-jumbotron">
        <%= article.content %>
    </h5>
    <p class="p-jumbotron">
        <%= link_to "Show more", article %>
    </p>
</div>

app/views/articles/_form.html.erb
    <div class="container">
        <%= form_with(model: @article, local: true) do |form| %>

            <div>
                <%= form.label :title %>
                <%= form.text_field :title, class: "form-control" %>
            </div>

            <div>
                <%= form.label :content %>
                <%= form.text_area :content, class: "form-control" %>
            </div>

            <div>
                <button type="submit" class="btn btn-secondary button">Save</button>
            </div>
        <%end %>
    </div>

app/views/articles/edit.html.erb
<div class="jumbotron">
    <div class="container">
        <h3><%= @article.title %></h3>
        <%= render "articles/form" %>
    </div>
</div>

app/views/articles/index.html.erb
<%= render @articles %>

app/views/articles/new.html.erb
<div class="jumbotron">
    <div class="container">
        <!-- <h3>Create new</h3> -->
        <%= render "articles/form" %>
    </div>
</div>

app/views/articles/show.html.erb
<div class="jumbotron">
    <h3>
        <%= @article.title %>
    </h3>
    <p>
        <%= @article.content %>
    </p>
    <div>
        <p><%= link_to "Delete", @article, method: :delete %>
        <%= link_to "Edit", "#{@article.id}/edit" %></p>
    </div>
</div>

app/views/home/index.html.erb
<h1></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Articles</title>
    <%=  csrf_meta_tags  %>
    <%=  csp_meta_tag  %>

    <%=  stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'  %>
    <%=  javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'  %>
  </head>

  <body>
    <%= render "partials/nav" %>

    <%=  yield  %>
  </body>
</html>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <%= link_to "Index", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "New", new_articles_path, class: "nav-link" %>
        </li>
    </ul>
</nav>